version: "3.0"

services:
  nginx: 
    image: nginx:1.21-alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./project/static:/usr/share/nginx/html/
    ports:
    - 80:80
    networks:
    - frontend


  db:
    image: postgres:9.5   # slim it down
    environment:
      POSTGRES_PASSWORD: gutendex
      #POSTGRES_DB: gutendex 
      #POSTGRES_USER: gutendex
      #POSTGRES_INITDB_ARGS: GRANT ALL PRIVILEGES ON DATABASE gutendex TO gutendex
    volumes:
      - wdata:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
     - '5432'
    networks:
      - backend
 
    


  app:
    build: ./project 
    ports:
    - '8000:8000'
    networks:
      - backend
      - frontend




volumes:
  wdata: 
networks:
  backend:
  frontend:


